name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - Unit_Test
  pull_request:
    branches:
      - "*"

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug Directory Structure  # ✅ Add this for debugging
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: FindMyClass  # ✅ Update with correct path
        run: npm install

      - name: Run Tests with Coverage
        working-directory: FindMyClass  # ✅ Update with correct path
        run: npm test -- --coverage --coverageReporters=lcov || true

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=antoinemansour7_minicap-soen390
            -Dsonar.organization=antoinemansour7
            -Dsonar.sources=FindMyClass  # ✅ Update with correct path
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.javascript.lcov.reportPaths=FindMyClass/coverage/lcov.info
            -Dsonar.coverage.exclusions=**/*.test.js,**/*.spec.js,jest.config.js,**/__tests__/**
            -Dsonar.exclusions=node_modules/**/*,.git/**/*,.github/**/*