name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - SonarQube
  pull_request:
    branches:
      - "*"

jobs:
  sonarQube:
    name: Run SonarQube Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SonarQube Scanner
        run: |
          curl -o sonarqube.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-4.7.0.2747-linux.zip
          unzip sonarqube.zip
          mv sonar-scanner-4.7.0.2747-linux sonar-scanner
          echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=antoinemansour7_miniCap \
            -Dsonar.projectName=MiniCap \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.sources=. \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=$SONAR_TOKEN