name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - SonarQube
  pull_request:
    branches:
      - "*"

jobs:
  sonarQube:
    name: Run SonarQube Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Cache SonarQube Scanner Cache
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarQube Scanner
        env:
          # This secret should be added in your repository's Settings > Secrets and variables > Actions
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=antoinemansour7_miniCap \
            -Dsonar.projectName=MiniCap \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.sources=. \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=$SONAR_TOKEN