name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - SonarQube
  pull_request:
    branches:
      - "*"

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=antoinemansour7_miniCap
            -Dsonar.organization=antoinemansour7
            -Dsonar.projectName=MiniCap
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.qualitygate.wait=true
            -Dsonar.javascript.node.maxspace=4096
            -Dsonar.coverage.exclusions=**/*.test.js,**/*.spec.js,jest.config.js
            -Dsonar.exclusions=node_modules/**/*
            -Dsonar.verbose=true
            -Dsonar.scm.provider=git
            -Dsonar.autoScan.enabled=false