name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Jest tests with coverage
      - name: Run tests and collect coverage
        run: npm test -- --coverage

      # Step 5: Install SonarScanner
      - name: Install SonarScanner
        run: |
          npm install -g sonar-scanner

      # Step 6: Run SonarCloud Analysis
      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=antoinemansour7_minicap-soen390 \
            -Dsonar.organization=antoinemansour7 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io/ \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.javascript.lcov.reportPaths=**/coverage/lcov.info \
            -Dsonar.coverage.exclusions=**/*.test.js,**/*.spec.js,**/jest.config.js,**/__tests__/**,**/babel.config.js,**/metro.config.js,**/jest.setup.js \
            -Dsonar.exclusions=**/node_modules/**,**/.git/**,**/.github/**,**/coverage/**,**/dist/**,**/build/**