name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - SonarQube
  pull_request:
    branches:
      - "*"

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for better relevancy of analysis
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Generate a token on SonarCloud.io
        with:
          # Additional arguments for the sonarcloud scanner
          args: >
            -Dsonar.projectKey=antoinemansour7_miniCap
            -Dsonar.organization=antoinemansour7
            -Dsonar.projectName=MiniCap
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8