name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - SonarQube
  pull_request:
    branches:
      - "*"

jobs:
  sonarQube:
    name: Run SonarQube Scanner
    runs-on: ubuntu-latest

    # Spin up a SonarQube server as a service container.
    services:
      sonarqube:
        image: sonarqube:community
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -f http://localhost:9000/api/system/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SonarQube Scanner
        run: |
          # Download the latest SonarScanner CLI (adjust the version if needed)
          wget -q -O sonarqube.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonarqube.zip
          mv sonar-scanner-cli-5.0.1.3006-linux sonar-scanner
          # Add the SonarScanner binary folder to the PATH
          echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Wait for SonarQube Server
        run: |
          echo "Waiting for SonarQube server to be ready..."
          for i in {1..20}; do
            if curl -s http://localhost:9000/api/system/health | grep -q '"status":"UP"'; then
              echo "SonarQube is up!"
              exit 0
            fi
            echo "Still waiting..."
            sleep 10
          done
          echo "SonarQube server did not start in time."
          exit 1

      - name: Run SonarQube Scanner
        env:
          # Make sure you have added your token to your repository secrets as SONAR_TOKEN
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=antoinemansour7_miniCap \
            -Dsonar.projectName=MiniCap \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.sources=. \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=$SONAR_TOKEN